# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SummaryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SummaryDialogWidget(object):
    def setupUi(self, SummaryDialogWidget):
        SummaryDialogWidget.setObjectName("SummaryDialogWidget")
        SummaryDialogWidget.resize(1017, 670)
        SummaryDialogWidget.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(SummaryDialogWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_widget = QtWidgets.QWidget(SummaryDialogWidget)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.header_widget)
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/bootstrap-icons-1.8.3/info.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.header_widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.header_widget)
        self.summaryDataTree_widget = QtWidgets.QWidget(SummaryDialogWidget)
        self.summaryDataTree_widget.setObjectName("summaryDataTree_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.summaryDataTree_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dataTree_Widget = QtWidgets.QTreeWidget(self.summaryDataTree_widget)
        self.dataTree_Widget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dataTree_Widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataTree_Widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.dataTree_Widget.setAutoScroll(True)
        self.dataTree_Widget.setTabKeyNavigation(True)
        self.dataTree_Widget.setProperty("showDropIndicator", True)
        self.dataTree_Widget.setAlternatingRowColors(True)
        self.dataTree_Widget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.dataTree_Widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.dataTree_Widget.setRootIsDecorated(True)
        self.dataTree_Widget.setUniformRowHeights(False)
        self.dataTree_Widget.setAnimated(True)
        self.dataTree_Widget.setAllColumnsShowFocus(False)
        self.dataTree_Widget.setWordWrap(True)
        self.dataTree_Widget.setHeaderHidden(False)
        self.dataTree_Widget.setExpandsOnDoubleClick(True)
        self.dataTree_Widget.setObjectName("dataTree_Widget")
        self.dataTree_Widget.header().setVisible(True)
        self.dataTree_Widget.header().setCascadingSectionResizes(True)
        self.dataTree_Widget.header().setHighlightSections(False)
        self.dataTree_Widget.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.dataTree_Widget)
        self.verticalLayout.addWidget(self.summaryDataTree_widget)
        self.toolButtons_widget = QtWidgets.QWidget(SummaryDialogWidget)
        self.toolButtons_widget.setObjectName("toolButtons_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toolButtons_widget)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.closeSummary_btn = QtWidgets.QPushButton(self.toolButtons_widget)
        self.closeSummary_btn.setCheckable(False)
        self.closeSummary_btn.setFlat(False)
        self.closeSummary_btn.setObjectName("closeSummary_btn")
        self.horizontalLayout_2.addWidget(self.closeSummary_btn)
        self.verticalLayout.addWidget(self.toolButtons_widget)

        self.retranslateUi(SummaryDialogWidget)
        QtCore.QMetaObject.connectSlotsByName(SummaryDialogWidget)

    def retranslateUi(self, SummaryDialogWidget):
        _translate = QtCore.QCoreApplication.translate
        SummaryDialogWidget.setWindowTitle(_translate("SummaryDialogWidget", "Summary "))
        self.label.setText(_translate("SummaryDialogWidget", "Conversion summary"))
        self.dataTree_Widget.setSortingEnabled(False)
        self.dataTree_Widget.headerItem().setText(0, _translate("SummaryDialogWidget", "ID"))
        self.dataTree_Widget.headerItem().setText(1, _translate("SummaryDialogWidget", "Old teststep"))
        self.dataTree_Widget.headerItem().setText(2, _translate("SummaryDialogWidget", "New teststep"))
        self.closeSummary_btn.setText(_translate("SummaryDialogWidget", "Close"))
        self.closeSummary_btn.setShortcut(_translate("SummaryDialogWidget", "Ctrl+W, Meta+W"))
import bootstrap_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SummaryDialogWidget = QtWidgets.QDialog()
    ui = Ui_SummaryDialogWidget()
    ui.setupUi(SummaryDialogWidget)
    SummaryDialogWidget.show()
    sys.exit(app.exec_())
