# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiWarningDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningDialog(object):
    def setupUi(self, WarningDialog):
        WarningDialog.setObjectName("WarningDialog")
        WarningDialog.resize(579, 438)
        WarningDialog.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(WarningDialog)
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_widget = QtWidgets.QWidget(WarningDialog)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WarningIcon_label = QtWidgets.QLabel(self.header_widget)
        self.WarningIcon_label.setMinimumSize(QtCore.QSize(0, 0))
        self.WarningIcon_label.setMaximumSize(QtCore.QSize(30, 30))
        self.WarningIcon_label.setText("")
        self.WarningIcon_label.setPixmap(QtGui.QPixmap(":/icons/bootstrap-icons-1.8.3/warning.png"))
        self.WarningIcon_label.setScaledContents(True)
        self.WarningIcon_label.setObjectName("WarningIcon_label")
        self.horizontalLayout.addWidget(self.WarningIcon_label)
        self.dialogTitle_label = QtWidgets.QLabel(self.header_widget)
        self.dialogTitle_label.setObjectName("dialogTitle_label")
        self.horizontalLayout.addWidget(self.dialogTitle_label)
        self.warningSourceFile_edit = QtWidgets.QLineEdit(self.header_widget)
        self.warningSourceFile_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warningSourceFile_edit.sizePolicy().hasHeightForWidth())
        self.warningSourceFile_edit.setSizePolicy(sizePolicy)
        self.warningSourceFile_edit.setMinimumSize(QtCore.QSize(400, 0))
        self.warningSourceFile_edit.setMaximumSize(QtCore.QSize(700, 23))
        self.warningSourceFile_edit.setText("")
        self.warningSourceFile_edit.setReadOnly(True)
        self.warningSourceFile_edit.setObjectName("warningSourceFile_edit")
        self.horizontalLayout.addWidget(self.warningSourceFile_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.header_widget)
        self.warningDataTreeMain_widget = QtWidgets.QWidget(WarningDialog)
        self.warningDataTreeMain_widget.setObjectName("warningDataTreeMain_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.warningDataTreeMain_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.warningsTab_widget = QtWidgets.QTabWidget(self.warningDataTreeMain_widget)
        self.warningsTab_widget.setIconSize(QtCore.QSize(10, 10))
        self.warningsTab_widget.setTabsClosable(False)
        self.warningsTab_widget.setTabBarAutoHide(False)
        self.warningsTab_widget.setObjectName("warningsTab_widget")
        self.verticalLayout_2.addWidget(self.warningsTab_widget)
        self.verticalLayout.addWidget(self.warningDataTreeMain_widget)
        self.toolButtons_widget = QtWidgets.QWidget(WarningDialog)
        self.toolButtons_widget.setObjectName("toolButtons_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toolButtons_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.editConfig_btn = QtWidgets.QPushButton(self.toolButtons_widget)
        self.editConfig_btn.setAutoDefault(False)
        self.editConfig_btn.setObjectName("editConfig_btn")
        self.horizontalLayout_2.addWidget(self.editConfig_btn)
        self.closeWarning_btn = QtWidgets.QPushButton(self.toolButtons_widget)
        self.closeWarning_btn.setCheckable(False)
        self.closeWarning_btn.setDefault(False)
        self.closeWarning_btn.setFlat(False)
        self.closeWarning_btn.setObjectName("closeWarning_btn")
        self.horizontalLayout_2.addWidget(self.closeWarning_btn)
        self.verticalLayout.addWidget(self.toolButtons_widget)

        self.retranslateUi(WarningDialog)
        self.warningsTab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(WarningDialog)

    def retranslateUi(self, WarningDialog):
        _translate = QtCore.QCoreApplication.translate
        WarningDialog.setWindowTitle(_translate("WarningDialog", "Summary "))
        WarningDialog.setStatusTip(_translate("WarningDialog", "Warnings raised by config file"))
        WarningDialog.setWhatsThis(_translate("WarningDialog", "Warnings raised by config file"))
        self.dialogTitle_label.setText(_translate("WarningDialog", "Config Warnings for:"))
        self.editConfig_btn.setToolTip(_translate("WarningDialog", "Open config file to edit"))
        self.editConfig_btn.setStatusTip(_translate("WarningDialog", "Open config file to edit"))
        self.editConfig_btn.setWhatsThis(_translate("WarningDialog", "Open config file to edit"))
        self.editConfig_btn.setText(_translate("WarningDialog", "Edit"))
        self.closeWarning_btn.setText(_translate("WarningDialog", "Close"))
        self.closeWarning_btn.setShortcut(_translate("WarningDialog", "Ctrl+W, Meta+W"))

from . import bootstrap_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WarningDialog = QtWidgets.QDialog()
    ui = Ui_WarningDialog()
    ui.setupUi(WarningDialog)
    WarningDialog.show()
    sys.exit(app.exec_())
