# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiNewFunctionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewFunctionDialog(object):
    def setupUi(self, NewFunctionDialog):
        NewFunctionDialog.setObjectName("NewFunctionDialog")
        NewFunctionDialog.resize(288, 435)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewFunctionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newFunctionFrom_widget = QtWidgets.QWidget(NewFunctionDialog)
        self.newFunctionFrom_widget.setObjectName("newFunctionFrom_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.newFunctionFrom_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newFunctionLibrary_box = QtWidgets.QGroupBox(self.newFunctionFrom_widget)
        self.newFunctionLibrary_box.setObjectName("newFunctionLibrary_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.newFunctionLibrary_box)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.functionLibrary_edit = QtWidgets.QLineEdit(self.newFunctionLibrary_box)
        self.functionLibrary_edit.setObjectName("functionLibrary_edit")
        self.horizontalLayout.addWidget(self.functionLibrary_edit)
        self.verticalLayout_2.addWidget(self.newFunctionLibrary_box)
        self.newFunctionName_box = QtWidgets.QGroupBox(self.newFunctionFrom_widget)
        self.newFunctionName_box.setObjectName("newFunctionName_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.newFunctionName_box)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.functionName_edit = QtWidgets.QLineEdit(self.newFunctionName_box)
        self.functionName_edit.setObjectName("functionName_edit")
        self.horizontalLayout_2.addWidget(self.functionName_edit)
        self.verticalLayout_2.addWidget(self.newFunctionName_box)
        self.newFunctionParameter_box = QtWidgets.QGroupBox(self.newFunctionFrom_widget)
        self.newFunctionParameter_box.setObjectName("newFunctionParameter_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.newFunctionParameter_box)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.functionParameterlist_widget = QtWidgets.QListWidget(self.newFunctionParameter_box)
        self.functionParameterlist_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.functionParameterlist_widget.setObjectName("functionParameterlist_widget")
        self.horizontalLayout_3.addWidget(self.functionParameterlist_widget)
        self.verticalLayout_2.addWidget(self.newFunctionParameter_box)
        self.verticalLayout.addWidget(self.newFunctionFrom_widget)
        self.dialogButton_box = QtWidgets.QDialogButtonBox(NewFunctionDialog)
        self.dialogButton_box.setOrientation(QtCore.Qt.Horizontal)
        self.dialogButton_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.dialogButton_box.setObjectName("dialogButton_box")
        self.verticalLayout.addWidget(self.dialogButton_box)

        self.retranslateUi(NewFunctionDialog)
        self.dialogButton_box.accepted.connect(NewFunctionDialog.accept) # type: ignore
        self.dialogButton_box.rejected.connect(NewFunctionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewFunctionDialog)

    def retranslateUi(self, NewFunctionDialog):
        _translate = QtCore.QCoreApplication.translate
        NewFunctionDialog.setWindowTitle(_translate("NewFunctionDialog", "Dialog"))
        self.newFunctionLibrary_box.setTitle(_translate("NewFunctionDialog", "Function library"))
        self.newFunctionName_box.setTitle(_translate("NewFunctionDialog", "Function Name"))
        self.newFunctionParameter_box.setTitle(_translate("NewFunctionDialog", "Function parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewFunctionDialog = QtWidgets.QDialog()
    ui = Ui_NewFunctionDialog()
    ui.setupUi(NewFunctionDialog)
    NewFunctionDialog.show()
    sys.exit(app.exec_())
